# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPLBAllowedForwardingRulesConstraintV2
metadata:
  name: gcp_lb_forwarding_rule_allowlist
  annotations:
    description: Verifies load balancer forwarding rules against allowed values.
spec:
  severity: high
  parameters:
    allowlist:
    - target: https://www.googleapis.com/compute/v1/projects/test-project/regions/us-east1/targetHttpProxies/test-noip-target-proxy
      load_balancing_scheme: EXTERNAL
      port_range: 80-80
      ip_protocol: TCP
      ip_address: "34.95.94.170"
    - target: https://www.googleapis.com/compute/v1/projects/test-project/regions/us-east1/targetHttpProxies/test-noip-target-proxy2
      load_balancing_scheme: INTERNAL
      port_range: 4500-4500
      ip_protocol: UDP
      ip_address: "198.51.100.99"
