# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

timeout: 1200s
steps:
- name: gcr.io/$PROJECT_ID/terraform
  entrypoint: /bin/bash
  args:
  - -c
  - |
    gcloud config set auth/impersonate_service_account ${_TF_SA_EMAIL}
# terraform init -input=false
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - init
  - -input=false
# terraform validate
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - validate
# terraform plan -input=false -out=tfplan
- name: gcr.io/$PROJECT_ID/terraform
  args:
  - plan
  - -input=false
  - -out=tfplan
artifacts:
  objects:
    location: 'gs://${_ARTIFACT_BUCKET_NAME}/terraform/cloudbuild/plan/$BUILD_ID'
    paths: ['cloudbuild-tf-plan.yaml', 'tfplan']
